"""Add Dress model

Revision ID: 49b59c71882e
Revises: ab33879808f3
Create Date: 2026-04-03 15:31:20.612259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b59c71882e'
down_revision: Union[str, Sequence[str], None] = 'ab33879808f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sizes', sa.String(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('ai_model_url', sa.String(), nullable=True),
    sa.Column('is_ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('boutique_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutique.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dress_id'), 'dress', ['id'], unique=False)
    op.create_index(op.f('ix_dress_name'), 'dress', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dress_name'), table_name='dress')
    op.drop_index(op.f('ix_dress_id'), table_name='dress')
    op.drop_table('dress')
    # ### end Alembic commands ###
