"""Add Boutique model

Revision ID: ab33879808f3
Revises: e270cbfe7ad1
Create Date: 2026-04-03 15:16:09.641519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab33879808f3'
down_revision: Union[str, Sequence[str], None] = 'e270cbfe7ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boutique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('header_image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boutique_id'), 'boutique', ['id'], unique=False)
    op.create_index(op.f('ix_boutique_location'), 'boutique', ['location'], unique=False)
    op.create_index(op.f('ix_boutique_name'), 'boutique', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boutique_name'), table_name='boutique')
    op.drop_index(op.f('ix_boutique_location'), table_name='boutique')
    op.drop_index(op.f('ix_boutique_id'), table_name='boutique')
    op.drop_table('boutique')
    # ### end Alembic commands ###
